on:
  push:    
    branches:    
      - master     

jobs:
  trigger-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
           repository: octodemo/testing-audit-log
           token: ${{ secrets.TOKEN }}
           event-type: test-suite
